name: Test

on:
  workflow_call:

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0.8
          extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Validate Composer
        run: composer validate

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-scripts

      - name: Copy testing environment config file
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"

      - name: Copy example environment config file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate Laravel encryption key
        run: php artisan key:generate

      - name: Run Tests
        run: ./vendor/bin/pest
        env:
          APP_ENV: testing

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
